/* ══════════════════════════════════════════════════════════════════════════════
   PBGen — مولّد صفحة الهبوط الذكي:
   ١) يبني «البرومبت السحري المزدوج» (نصوص بيع + برومبت تصميم لـ Nano Banana) بـ 7 لغات، تنسخه إلى Gemini/ChatGPT.
   ٢) يستورد صورة الصفحة الطويلة الناتجة ويحوّلها إلى صفحة قابلة للتعديل في منشئ الصفحات:
      تقطيع إلى أقسام (حدود مقترحة تلقائياً وقابلة للضبط) + استخراج النصوص (OCR داخل المتصفح بلا مفاتيح API)
      إلى عناصر نصية حرة + محو النص المخبوز من الصورة حيث الخلفية بسيطة. الأقسام «متناسبة» فتتحجم مع الشاشة.
   ══════════════════════════════════════════════════════════════════════════════ */
const PBGen = (() => {
  const esc = s => String(s == null ? "" : s).replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const $ = id => document.getElementById(id);

  /* ───────────── 1) البرومبت ───────────── */
  const LANGS = {
    ar: { label: "العربية (الأسواق المحلية والخليج)", name: "Arabic", rtl: true, tess: "ara+eng", trust: "ثقة عملائنا", limited: "⚠️ الكمية المتاحة محدودة جداً، اطلب الآن!", cta: "اطلب الآن - الدفع عند الاستلام" },
    ma: { label: "الدارجة المغربية (السوق المغربي - COD)", name: "Moroccan Darija (written in Arabic script)", rtl: true, tess: "ara+eng", trust: "ثقة زبائننا", limited: "⚠️ الكمية محدودة بزاف، طلب دابا!", cta: "طلب دابا - الأداء عند التوصيل" },
    en: { label: "الإنجليزية (الأسواق العالمية والدروبشيبينغ)", name: "English", rtl: false, tess: "eng", trust: "Trusted by Our Customers", limited: "⚠️ Limited stock available, order now!", cta: "ORDER NOW - CASH ON DELIVERY" },
    fr: { label: "الفرنسية (إفريقيا وأوروبا الناطقة بالفرنسية)", name: "French", rtl: false, tess: "fra+eng", trust: "La confiance de nos clients", limited: "⚠️ Quantité très limitée, commandez maintenant !", cta: "COMMANDER - PAIEMENT À LA LIVRAISON" },
    es: { label: "الإسبانية (أمريكا اللاتينية وإسبانيا)", name: "Spanish", rtl: false, tess: "spa+eng", trust: "La confianza de nuestros clientes", limited: "⚠️ ¡Cantidad muy limitada, pide ahora!", cta: "PEDIR AHORA - PAGO CONTRA ENTREGA" },
    it: { label: "الإيطالية (السوق الإيطالي)", name: "Italian", rtl: false, tess: "ita+eng", trust: "La fiducia dei nostri clienti", limited: "⚠️ Quantità molto limitata, ordina ora!", cta: "ORDINA ORA - PAGAMENTO ALLA CONSEGNA" },
    de: { label: "الألمانية (السوق الألماني وأوروبا الوسطى)", name: "German", rtl: false, tess: "deu+eng", trust: "Das Vertrauen unserer Kunden", limited: "⚠️ Nur begrenzte Menge verfügbar, jetzt bestellen!", cta: "JETZT BESTELLEN - ZAHLUNG BEI LIEFERUNG" },
  };
  function buildPrompt(o) {
    const L = LANGS[o.lang] || LANGS.ar, bundle = o.offer === "bundle", ar = L.rtl;
    const ph = (arText, enText) => "[" + (ar ? arText : enText + " in " + L.name) + "]";
    const out = [];
    out.push(bundle
      ? "=== CRITICAL INSTRUCTION: PRODUCT BUNDLE ===\nNote: This landing page is for a BUNDLE / PACK of multiple products. Emphasize the combined value, the savings and the complete solution the bundle offers.\n============================================\n"
      : "=== CRITICAL INSTRUCTION: SINGLE PRODUCT ===\nNote: This landing page is for a SINGLE product. Focus on its core individual benefits.\n============================================\n");
    const det = [];
    if (o.name) det.push("- Product Name: " + o.name);
    if (o.desc) det.push("- Product Description/Benefits: " + o.desc);
    if (o.price) det.push("- Price: " + o.price);
    if (o.colors) det.push("- Design Colors: " + o.colors);
    if (det.length) out.push("=== SPECIFIC PRODUCT DETAILS PROVIDED BY THE USER ===\nPlease strictly use the following details in your copywriting instead of guessing them:\n" + det.join("\n") + "\n=====================================================\n");
    if (o.colors) out.push("=== CRITICAL INSTRUCTION: DESIGN COLORS ===\nThe user specified the following color palette: \"" + o.colors + "\".\nIn Step 2 (Design Prompt), you MUST replace \"[insert dynamic colors matching product image]\" with these specific colors.\n===========================================\n");
    out.push(`Analyze the uploaded product image. Identify the product, its key features, target audience, and best color palette. Act as a world-class ${L.name} Direct Response Copywriter and AI Prompt Engineer specializing in image-based mobile-first landing pages generated by 'Nano Banana Pro'.

### YOUR MISSION HAS TWO CRITICAL STEPS:

### STEP 1: TEXT GENERATION (COPYWRITING)
First, write highly persuasive ${L.name} sales copy for this specific product based on the structure and instructions required below. Present this copy clearly in your response so I can read it, review it, and use it.

### STEP 2: NANO BANANA PRO DESIGN PROMPT
After presenting the copywriting, output a single, consolidated READY-TO-COPY design prompt for the "Nano Banana Pro" image generator.

---

### CRITICAL INSTRUCTIONS FOR STEP 2 OUTPUT:
1. Output Format: Provide the entire design prompt inside a single code block.
2. Product Context: In all sections, explicitly describe the product visually. Ensure the layout handles either a single floating item OR a product bundle/package as a group.
3. Visual Descriptions: Add strong, creative English visual descriptions for each section based on the uploaded image.
4. ${L.name} Typography (MANDATORY): ALL ${L.name} text MUST be rendered in massive, extremely bold fonts, with a minimum size of 20px equivalent. Render ONLY the generated ${L.name} text inside the quotation marks " ". ABSOLUTELY DO NOT render any English structural words or labels (like Headline, Body Text, Visual Flow)${ar ? "" : " unless the target language is English"}.
5. Brackets and Label Removal: Before providing the final code, fill all [bracketed placeholders] with the precise ${L.name} text you generated, and remove all structural labels from the output.
6. Text Direction: ${ar ? "All text and layout direction must respect right-to-left flow." : "All text and layout direction must respect left-to-right flow."}

--- USE THIS EXACT TEMPLATE FOR STEP 2 (DESIGN PROMPT) ---

Act as a world-class Mobile E-commerce Designer. Generate an ultra-long vertical infographic landing page IMAGE (aspect ratio 9:32 or longer) for the [identify product bundle OR single product] in the uploaded image.

CRITICAL FORMAT RULE: DO NOT write any HTML, CSS, UI code, or text-based code. You MUST generate a purely visual, single continuous graphical IMAGE.

AESTHETIC & FLOW INSTRUCTIONS:
Create one continuous journey with smooth color gradients (specifically [insert dynamic colors matching product image]) and subtle kinetic lines. No hard dividing lines. Use a dynamic background matching the [insert product vibe]. Feature the product repeatedly.

* Dynamic background with particle effects. Product is prominent. Small Yellow Text: "${ph("اكتب: الأكثر مبيعاً أو جديد", "write: Best Seller or New")}"
* HUGE WHITE BOLD TEXT: "${ph("عنوان رئيسي جذاب وقوي جداً", "very strong, catchy main headline")}"
* Large Text: "${ph("جملة تشرح الفائدة الكبرى للمنتج", "one sentence explaining the product's biggest benefit")}"

* Smooth transition to a muted area. Feature a negative color shift and problem icons. Large Bold Red Text: "${ph("سؤال يلمس مشكلة العميل", "a question touching the customer's problem")}"
* Medium Black Text: "${ph("اشرح المشكلة باختصار", "briefly explain the problem")}"

* Burst of bright light transitioning to a clean background. Product appears triumphantly with glowing effects. HUGE BOLD COLORED TEXT: "${ph("عنوان يقدم المنتج كحل نهائي", "headline presenting the product as the final solution")}"
* Large Black Text: "${ph("جملة تؤكد قوة الحل", "sentence confirming the power of the solution")}"

* Side-by-side layout with a clear visual contrast. Left side is dark/dull showing [describe problem visually]. Right side is bright/vibrant showing [describe happy state]. LARGE BOLD COLORED TEXT: "${ph("عنوان جذاب للفرق قبل وبعد", "catchy before/after headline")}"
* Medium Red Text: "❌ ${ph("قبل: وصف قصير للمعاناة", "Before: short description of the struggle")}"
* Medium Green Text: "✅ ${ph("بعد: وصف قصير للراحة", "After: short description of the relief")}"

* Extreme close-up on [describe feature visually]. Use glowing effects. LARGE BOLD COLORED TEXT: "${ph("عنوان الميزة الأولى", "first feature headline")}"
* Large Black Text: "${ph("شرح قوي للميزة", "strong explanation of the feature")}"

* 2-Column Split Layout. Left Column is glowing OUR PRODUCT. Right Column is dull Gray generic competitor. LARGE BOLD COLORED TEXT: "${ph("عنوان يقارن ويثبت التفوق", "headline comparing and proving superiority")}"
* Medium Green Text: "✔️ ${ph("ميزة 1", "advantage 1")}\\n✔️ ${ph("ميزة 2", "advantage 2")}"
* Medium Red Text: "❌ ${ph("عيب 1", "drawback 1")}\\n❌ ${ph("عيب 2", "drawback 2")}"

* Lifestyle visual of [describe a scene with the product in use]. LARGE BOLD COLORED TEXT: "${ph("عنوان عن فائدة المنتج يومياً", "headline about the daily benefit")}"
* Large Black Text: "${ph("كيف يحسن المنتج حياة الزبون", "how the product improves the customer's life")}"

* 5 large glowing stars ★★★★★ centered. Customer icons. LARGE BOLD BLACK TEXT: "${L.trust}"
* Medium Black Text: "${ph("مراجعة إيجابية قصيرة بلسان زبون", "short positive review in a customer's voice")}"

* Solid, high-contrast footer. Product prominent next to CTA button. LARGE BOLD TEXT: "${ph("اذكر السعر بوضوح", "state the price clearly")}"
* Large White Bold Text: "${L.limited}"
* HUGE BLACK TEXT on YELLOW Button: "${L.cta}"`);
    return out.join("\n");
  }

  /* ───────────── 2) تحليل الصورة ───────────── */
  const loadImage = file => new Promise((res, rej) => { const url = URL.createObjectURL(file), im = new Image(); im.onload = () => { const c = document.createElement("canvas"); c.width = im.naturalWidth; c.height = im.naturalHeight; c.getContext("2d").drawImage(im, 0, 0); URL.revokeObjectURL(url); res(c); }; im.onerror = () => rej(new Error("تعذّرت قراءة الصورة")); im.src = url; });

  /* حدود مقترحة: n-1 خطاً قرب المواضع المتساوية، يُختار فيها أهدأ صف (أقل تغيّراً عمودياً وأفقياً) */
  function suggestCuts(canvas, n) {
    n = Math.max(1, Math.min(30, Math.round(n))); if (n === 1) return [];
    const W = canvas.width, H = canvas.height, sw = 72, sh = Math.max(n * 4, Math.round(H * sw / W)), sm = document.createElement("canvas"); sm.width = sw; sm.height = sh;
    const g = sm.getContext("2d", { willReadFrequently: true }); g.drawImage(canvas, 0, 0, sw, sh); const d = g.getImageData(0, 0, sw, sh).data, sc = [];
    const px = (x, y) => { const i = (y * sw + x) * 4; return [d[i], d[i + 1], d[i + 2]]; };
    for (let y = 0; y < sh; y++) { let e = 0; for (let x = 0; x < sw; x++) { const a = px(x, y), b = px(x, Math.min(sh - 1, y + 1)), c = px(Math.min(sw - 1, x + 1), y); e += Math.abs(a[0] - b[0]) + Math.abs(a[1] - b[1]) + Math.abs(a[2] - b[2]) + 0.7 * (Math.abs(a[0] - c[0]) + Math.abs(a[1] - c[1]) + Math.abs(a[2] - c[2])); } sc.push(e / sw); }
    const sm3 = sc.map((_, y) => ((sc[y - 1] ?? sc[y]) + sc[y] + (sc[y + 1] ?? sc[y])) / 3), cuts = [], seg = sh / n; let last = 0;
    for (let i = 1; i < n; i++) { const t = Math.round(i * seg), lo = Math.max(last + Math.round(seg * .4), t - Math.round(seg * .35)), hi = Math.min(sh - 2, t + Math.round(seg * .35)); let best = Math.min(Math.max(t, lo), hi), bv = Infinity; for (let y = lo; y <= hi; y++) if (sm3[y] < bv) { bv = sm3[y]; best = y; } cuts.push(Math.round(best * H / sh)); last = best; }
    return cuts;
  }

  /* OCR داخل المتصفح (Tesseract.js من CDN، بلا مفتاح). يمكن استبداله (للاختبار) بتعيين PBGen.ocr */
  async function ensureTesseract() {
    if (window.Tesseract) return; await new Promise((res, rej) => { const s = document.createElement("script"); s.src = "https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js"; s.onload = res; s.onerror = () => rej(new Error("تعذّر تحميل محرك OCR (تحقق من الإنترنت)")); document.head.appendChild(s); });
  }
  async function defaultOcr(canvas, lang, log) {
    await ensureTesseract(); const r = await Tesseract.recognize(canvas, lang || "ara+eng", { logger: m => log && log(m) });
    const lines = r.data.lines || ((r.data.blocks || []).flatMap(b => (b.paragraphs || []).flatMap(p => p.lines || [])));
    return lines.map(l => ({ text: String(l.text || "").replace(/\s+/g, " ").trim(), conf: l.confidence, bbox: l.bbox })).filter(l => l.text.length >= 2 && l.conf >= 40);
  }

  /* ألوان الصندوق: لون الخلفية (وسيط الحلقة المحيطة) ولون الحبر + هل الخلفية بسيطة بما يكفي للمحو */
  function analyze(ctx, W, H, b) {
    const pad = Math.max(8, Math.round((b.y1 - b.y0) * .3)), x0 = Math.max(0, Math.floor(b.x0 - pad)), y0 = Math.max(0, Math.floor(b.y0 - pad)), x1 = Math.min(W, Math.ceil(b.x1 + pad)), y1 = Math.min(H, Math.ceil(b.y1 + pad));
    const bw = x1 - x0, bh = y1 - y0; if (bw < 4 || bh < 4) return null; const d = ctx.getImageData(x0, y0, bw, bh).data, at = (x, y) => { const i = (y * bw + x) * 4; return [d[i], d[i + 1], d[i + 2]]; };
    const ring = []; for (let x = 0; x < bw; x++) { ring.push(at(x, 0), at(x, bh - 1)); } for (let y = 0; y < bh; y++) { ring.push(at(0, y), at(bw - 1, y)); }
    const med = i => { const a = ring.map(p => p[i]).sort((p, q) => p - q); return a[a.length >> 1]; }, bg = [med(0), med(1), med(2)], dist = p => Math.abs(p[0] - bg[0]) + Math.abs(p[1] - bg[1]) + Math.abs(p[2] - bg[2]);
    const inner = []; for (let y = pad; y < bh - pad; y++) for (let x = pad; x < bw - pad; x++) inner.push(at(x, y));
    inner.sort((p, q) => dist(q) - dist(p)); const top = inner.slice(0, Math.max(1, Math.round(inner.length * .06))), ink = [0, 1, 2].map(i => Math.round(top.reduce((a, p) => a + p[i], 0) / top.length));
    /* بساطة الخلفية: انحراف الحلقة عن الاستكمال الخطي بين الحافتين الأفقيتين */
    let err = 0, n = 0; for (let y = 0; y < bh; y++) { const L = at(0, y), R = at(bw - 1, y); for (const x of [0, bw - 1]) { /* حواف فقط */ } }
    for (const y of [0, bh - 1]) { const L = at(0, y), R = at(bw - 1, y); for (let x = 0; x < bw; x += 2) { const t = x / (bw - 1), p = at(x, y); err += Math.abs(p[0] - (L[0] + (R[0] - L[0]) * t)) + Math.abs(p[1] - (L[1] + (R[1] - L[1]) * t)) + Math.abs(p[2] - (L[2] + (R[2] - L[2]) * t)); n++; } }
    err /= (n * 3 || 1);
    const hex = c => "#" + c.map(v => v.toString(16).padStart(2, "0")).join("");
    return { bg: hex(bg), ink: hex(ink), contrast: dist(ink) / 3, err, rect: { x0, y0, x1, y1 } };
  }
  /* محو النص: استكمال خطي أفقي بين لوني الحافتين اليمنى واليسرى لكل صف */
  function erase(ctx, rect) {
    const { x0, y0, x1, y1 } = rect, w = x1 - x0, h = y1 - y0; if (x0 < 3 || w < 6) return; const img = ctx.getImageData(x0, y0, w, h), d = img.data, edge = (x, y) => ctx.getImageData(x, y, 3, 1).data;
    for (let y = 0; y < h; y++) { const l = edge(Math.max(0, x0 - 3), y0 + y), r = edge(Math.min(ctx.canvas.width - 3, x1), y0 + y), L = [0, 1, 2].map(i => (l[i] + l[4 + i] + l[8 + i]) / 3), R = [0, 1, 2].map(i => (r[i] + r[4 + i] + r[8 + i]) / 3);
      for (let x = 0; x < w; x++) { const t = x / Math.max(1, w - 1), i = (y * w + x) * 4; d[i] = L[0] + (R[0] - L[0]) * t; d[i + 1] = L[1] + (R[1] - L[1]) * t; d[i + 2] = L[2] + (R[2] - L[2]) * t; d[i + 3] = 255; } }
    ctx.putImageData(img, x0, y0);
  }

  /* تضييق الصندوق إلى حدود الحبر الفعلية (يصحّح انحراف OCR/Gemini): البكسل «حبر» إن بعُد عن استكمال الخلفية الخطي بين حافتي الصندوق */
  function refineBox(ctx, W, H, b) {
    const pad = Math.max(6, Math.round((b.y1 - b.y0) * .3)), x0 = Math.max(0, Math.floor(b.x0 - pad)), y0 = Math.max(0, Math.floor(b.y0 - pad)), x1 = Math.min(W, Math.ceil(b.x1 + pad)), y1 = Math.min(H, Math.ceil(b.y1 + pad)), w = x1 - x0, h = y1 - y0;
    if (w < 8 || h < 8) return b; const d = ctx.getImageData(x0, y0, w, h).data; let mnx = w, mxx = -1, mny = h, mxy = -1, n = 0;
    for (let y = 0; y < h; y++) { const li = (y * w) * 4, ri = (y * w + w - 1) * 4;
      for (let x = 0; x < w; x++) { const i = (y * w + x) * 4, t = x / (w - 1), e = Math.abs(d[i] - (d[li] + (d[ri] - d[li]) * t)) + Math.abs(d[i + 1] - (d[li + 1] + (d[ri + 1] - d[li + 1]) * t)) + Math.abs(d[i + 2] - (d[li + 2] + (d[ri + 2] - d[li + 2]) * t));
        if (e > 110) { n++; if (x < mnx) mnx = x; if (x > mxx) mxx = x; if (y < mny) mny = y; if (y > mxy) mxy = y; } } }
    if (n < 12 || mxx < 0) return b; return { x0: x0 + mnx, x1: x0 + mxx + 1, y0: y0 + mny, y1: y0 + mxy + 1 };
  }
  /* Gemini رؤية: يقرأ النص بدقة أعلى للعربية ويعيد صناديقه (box_2d مُطبَّعة 0-1000)؛ المفتاح مفتاحك المخزَّن في المتصفح فقط */
  async function geminiOcr(canvas, key, langName) {
    const W = canvas.width, H = canvas.height, c2 = document.createElement("canvas"), k = Math.min(1, 1600 / W); c2.width = Math.round(W * k); c2.height = Math.round(H * k); c2.getContext("2d").drawImage(canvas, 0, 0, c2.width, c2.height);
    const b64 = c2.toDataURL("image/jpeg", .9).split(",")[1];
    const prompt = `You are a precise OCR engine. The image is ${W}x${H} pixels and its text language is ${langName}. Read EVERY visible line of text exactly as written (keep the original script, digits, emojis and punctuation; never translate, correct or add words). Return ONLY JSON: {"lines":[{"text":"...","box_2d":[ymin,xmin,ymax,xmax]}]} where box_2d is normalized to 0-1000 relative to the image and fits tightly around that single line's glyphs. One entry per visual line, ordered top to bottom. If there is no text return {"lines":[]}.`;
    const o = await geminiJson(key, b64, prompt);
    return (o.lines || []).filter(l => l && l.text && Array.isArray(l.box_2d) && l.box_2d.length === 4).map(l => { const [ymin, xmin, ymax, xmax] = l.box_2d.map(Number); return { text: String(l.text).replace(/\s+/g, " ").trim(), conf: 95, bbox: { x0: xmin / 1000 * W, y0: ymin / 1000 * H, x1: xmax / 1000 * W, y1: ymax / 1000 * H } }; }).filter(l => l.text.length >= 1 && l.bbox.x1 > l.bbox.x0 && l.bbox.y1 > l.bbox.y0);
  }
  /* استدعاء Gemini بصورة + تعليمات ويعيد JSON؛ يجرّب أكثر من نموذج عند الازدحام */
  async function geminiJson(key, b64, prompt) {
    const models = ["gemini-3.8-flash", "gemini-2.5-flash", "gemini-3.8-flash"]; let last = "";
    for (let mi = 0; mi < models.length; mi++) {
      if (mi === models.length - 1) await new Promise(r => setTimeout(r, 3000));
      const r = await fetch("https://generativelanguage.googleapis.com/v1beta/models/" + models[mi] + ":generateContent", { method: "POST", headers: { "Content-Type": "application/json", "x-goog-api-key": key }, body: JSON.stringify({ contents: [{ parts: [{ inline_data: { mime_type: "image/jpeg", data: b64 } }, { text: prompt }] }], generationConfig: { responseMimeType: "application/json", temperature: 0 } }) });
      const j = await r.json().catch(() => ({}));
      if (!r.ok) { last = (j.error && j.error.message) || ("Gemini " + r.status); if ([404, 429, 500, 503].includes(r.status) || /no longer available|not found|not supported|high demand|overloaded|quota/i.test(last)) continue; throw new Error(last); }
      const t = ((((j.candidates || [])[0] || {}).content || {}).parts || []).map(x => x.text || "").join(""), m = t.match(/\{[\s\S]*\}/); if (!m) throw new Error("ردّ غير مفهوم من Gemini");
      return JSON.parse(m[0]);
    }
    throw new Error(last || "لا يوجد نموذج Gemini متاح");
  }
  /* اكتشاف تلقائي لمناطق المنتج/الصور/الأيقونات (غير النصية) ليُقصّ كلٌّ منها كعنصر مستقل */
  async function geminiDetect(canvas, key) {
    const W = canvas.width, H = canvas.height, c2 = document.createElement("canvas"), k = Math.min(1, 1400 / W); c2.width = Math.round(W * k); c2.height = Math.round(H * k); c2.getContext("2d").drawImage(canvas, 0, 0, c2.width, c2.height);
    const prompt = `This is a marketing landing-page image. List the distinct VISUAL objects that should be separated as independent images: the product(s) / product packaging / jars / bottles, people, food or ingredient photos, badges, seals, and standalone illustrations or icons. Do NOT include plain text, headlines, buttons, or the background. Return ONLY JSON: {"objects":[{"label":"short name","box_2d":[ymin,xmin,ymax,xmax]}]} with box_2d normalized 0-1000, fitting tightly around each object. At most 12 objects. If none, {"objects":[]}.`;
    const o = await geminiJson(key, c2.toDataURL("image/jpeg", .85).split(",")[1], prompt);
    return (o.objects || []).filter(x => x && Array.isArray(x.box_2d) && x.box_2d.length === 4).map(x => { const [a, b, c, d] = x.box_2d.map(Number); return { x0: Math.max(0, b / 1000 * W), y0: Math.max(0, a / 1000 * H), x1: Math.min(W, d / 1000 * W), y1: Math.min(H, c / 1000 * H), label: x.label }; }).filter(r => r.x1 - r.x0 > W * .04 && r.y1 - r.y0 > W * .04 && (r.x1 - r.x0) * (r.y1 - r.y0) < W * H * .6);
  }
  /* remove.bg: قص خلفية الصورة (PNG شفاف). قد يمنع المتصفح الاتصال المباشر (CORS) — عندها استعمل «قص كصورة» أو ارفع صورة مقصوصة يدوياً */
  async function removeBgCall(blob, key) {
    const fd = new FormData(); fd.append("image_file", blob, "cut.png"); fd.append("size", "auto"); fd.append("format", "png");
    let r; try { r = await fetch("https://api.remove.bg/v1.0/removebg", { method: "POST", headers: { "X-Api-Key": key }, body: fd }); } catch (e) { throw new Error("تعذّر الاتصال بـ remove.bg من المتصفح (قد يكون CORS أو الإنترنت)"); }
    if (!r.ok) { const j = await r.json().catch(() => ({})); throw new Error((j.errors && j.errors[0] && (j.errors[0].title + (j.errors[0].detail ? ": " + j.errors[0].detail : ""))) || ("remove.bg " + r.status)); }
    return await r.blob();
  }
  const cropBlob = (canvas, r, type) => new Promise(res => { const c = document.createElement("canvas"); c.width = Math.max(1, Math.round(r.x1 - r.x0)); c.height = Math.max(1, Math.round(r.y1 - r.y0)); c.getContext("2d").drawImage(canvas, Math.round(r.x0), Math.round(r.y0), c.width, c.height, 0, 0, c.width, c.height); c.toBlob(res, type || "image/png"); });

  /* دمج الأسطر المتجاورة المتشابهة (الارتفاع/المحاذاة) في كتل نصية */
  function groupLines(lines, W) {
    const ls = lines.slice().sort((a, b) => a.bbox.y0 - b.bbox.y0), blocks = [];
    ls.forEach(l => { const h = l.bbox.y1 - l.bbox.y0, cx = (l.bbox.x0 + l.bbox.x1) / 2, last = blocks[blocks.length - 1];
      if (last) { const lh = last.y1 - last.lastY0, near = l.bbox.y0 - last.y1 < lh * .9, sim = Math.abs(h - lh) < lh * .22, al = Math.abs(cx - last.cx) < W * .12 || Math.abs(l.bbox.x1 - last.x1) < W * .05; if (near && sim && al) { last.lines.push(l.text); last.x0 = Math.min(last.x0, l.bbox.x0); last.x1 = Math.max(last.x1, l.bbox.x1); last.y1 = l.bbox.y1; last.lastY0 = l.bbox.y0; last.cx = (last.x0 + last.x1) / 2; return; } }
      blocks.push({ lines: [l.text], x0: l.bbox.x0, x1: l.bbox.x1, y0: l.bbox.y0, y1: l.bbox.y1, lastY0: l.bbox.y0, cx, lineH: h }); });
    return blocks;
  }

  /* التحويل الكامل: صورة + حدود ⟵ صفحة (أقسام حرة متناسبة) */
  async function convert(o) {
    const C = o.canvas, W = C.width, dw = o.dw || 720, f = dw / W, bounds = [0].concat(o.cuts.slice().sort((a, b) => a - b), [C.height]);
    const sections = []; const log = o.onProgress || (() => { });
    for (let i = 0; i < bounds.length - 1; i++) {
      const y0 = bounds[i], y1 = bounds[i + 1], h = y1 - y0; if (h < 20) continue;
      log(`القسم ${i + 1} من ${bounds.length - 1}…`);
      const band = document.createElement("canvas"); band.width = W; band.height = h; const ctx = band.getContext("2d", { willReadFrequently: true }); ctx.drawImage(C, 0, y0, W, h, 0, 0, W, h);
      const widgets = [], cuts = [];
      /* مناطق القص (منتج/صور): تُقصّ من الصورة الأصلية قبل أي محو */
      for (const [ri, rg] of (o.regions || []).entries()) {
        const cy = (rg.y0 + rg.y1) / 2; if (cy < y0 || cy >= y1) continue;
        const r = { x0: Math.max(0, rg.x0), x1: Math.min(W, rg.x1), y0: Math.max(0, rg.y0 - y0), y1: Math.min(h, rg.y1 - y0) }; if (r.x1 - r.x0 < 16 || r.y1 - r.y0 < 16) continue;
        log(`قص منطقة ${ri + 1}…`); let blob = await cropBlob(band, r, "image/png"), cut = false;
        if (o.rbKey) { try { blob = await (PBGen.removeBg || removeBgCall)(blob, o.rbKey); cut = true; } catch (e) { log("⚠️ " + e.message + " — قُصّت كصورة عادية"); } }
        cuts.push({ r, blob, cut, a: o.eraseOrig !== false ? analyze(ctx, W, h, r) : null });
      }
      if (o.ocr) {
        let lines = []; try {
          const eng = PBGen.ocr || (o.engine === "gemini" && o.gkey ? (cv => geminiOcr(cv, o.gkey, o.langName || "Arabic")) : defaultOcr);
          lines = await eng(band, o.tess, m => { if (m && m.status && m.progress != null) log(`القسم ${i + 1}: ${m.status} ${Math.round(m.progress * 100)}%`); });
        } catch (e) { log("⚠️ " + e.message); }
        if (o.refine !== false) lines = lines.map(l => Object.assign({}, l, { bbox: refineBox(ctx, W, h, l.bbox) }));
        const blocks = groupLines(lines, W).map(b => Object.assign(b, { a: analyze(ctx, W, h, { x0: b.x0, y0: b.y0, x1: b.x1, y1: b.y1 }) })).filter(b => b.a);
        blocks.forEach(b => { b.ok = b.a.err < (o.maxErr || 34) && b.a.contrast > 70; });
        // نحلل الألوان قبل المحو (analyze أعلاه)، ثم نمحو كل الكتل المقبولة
        blocks.filter(b => b.ok).forEach(b => erase(ctx, b.a.rect));
        blocks.filter(b => b.ok).forEach((b, k) => {
          const bw = b.x1 - b.x0, padX = W * .04, n = b.lines.length, fsImg = Math.max(8, b.lineH * .72), centered = Math.abs(b.cx - W / 2) < W * .1, align = centered ? "center" : (b.cx > W / 2 ? "start" : "end");
          const x0 = Math.max(0, b.x0 - padX), x1 = Math.min(W, b.x1 + padX), type = n === 1 ? "heading" : "text";
          const wdg = PB.mkW(type, type === "heading" ? { text: b.lines[0], tag: "div" } : { html: "<p>" + b.lines.map(esc).join("<br>") + "</p>" });
          Object.assign(wdg.set, { color: b.a.ink, fs: { d: Math.round(fsImg * f) }, fw: "800", lh: { d: 1.3 }, ta: { d: align }, fx: { d: Math.round(x0 / W * 1000) / 10 }, fy: { d: Math.round(b.y0 * f) }, fwd: { d: Math.round((x1 - x0) / W * 1000) / 10 }, fh: { d: Math.max(10, Math.round((b.y1 - b.y0) * f)) }, zi: 2 + k });
          widgets.push(wdg);
        });
      }
      cuts.forEach((c, k) => { if (c.a && c.a.err < (o.maxErr || 34)) erase(ctx, { x0: Math.round(c.r.x0), y0: Math.round(c.r.y0), x1: Math.round(c.r.x1), y1: Math.round(c.r.y1) }); });       // مسح الأصل من الخلفية حيث تسمح بساطتها
      for (const [k, c] of cuts.entries()) {
        const path = await (o.upload ? o.upload(c.blob, "gen-cut-" + Date.now().toString(36) + "-" + i + "-" + k) : new Promise(res => { const fr = new FileReader(); fr.onload = () => res(fr.result); fr.readAsDataURL(c.blob); }));
        const im = PB.mkFree("image", 0, 0, 1); Object.assign(im.set, { src: path, fit: c.cut ? "contain" : "cover", fx: { d: Math.round(c.r.x0 / W * 1000) / 10 }, fy: { d: Math.round(c.r.y0 * f) }, fwd: { d: Math.round((c.r.x1 - c.r.x0) / W * 1000) / 10 }, fh: { d: Math.round((c.r.y1 - c.r.y0) * f) }, zi: 1, alt: "" }); widgets.push(im);
      }
      const blob = await new Promise(r => band.toBlob(r, "image/webp", .92));
      const path = await (o.upload ? o.upload(blob, "gen-" + Date.now().toString(36) + "-" + i) : Promise.resolve(band.toDataURL("image/webp", .9)));
      const bg = PB.mkFree("image", 0, 0, 0); Object.assign(bg.set, { src: path, fit: "fill", fx: { d: 0 }, fy: { d: 0 }, fwd: { d: 100 }, fh: { d: Math.round(h * f) }, zi: 0 });
      const sec = PB.mkCanvas(); Object.assign(sec.set, { scaled: true, dw, layout: "boxed", cw: { d: dw }, mh: { d: Math.round(h * f) } }); sec.free = [bg].concat(widgets); sections.push(sec);
    }
    const page = PB.newPage(o.title || "صفحة هبوط", o.slug || ""); page.sections = sections; page.header = false; page.footer = false; page.bg = "#ffffff";
    return page;
  }

  /* ───────────── الواجهة داخل تبويب «بناء الصفحات المتقدم» ───────────── */
  const S = { canvas: null, cuts: [], regions: [], file: null, regionMode: false };
  function mount(host) {
    host.innerHTML = `
<div class="card" id="gen-card" style="margin-bottom:1rem">
  <b style="color:var(--green);font-size:1.05rem">🪄 مولّد صفحة هبوط بالذكاء الاصطناعي — من صورة منتجك إلى صفحة قابلة للتعديل</b>
  <div class="hint" style="margin:.6rem 0">① انسخ «البرومبت السحري» وأرسله مع صورة منتجك إلى Gemini أو ChatGPT ← تحصل على نصوص بيع + برومبت تصميم. ② ضعه في Nano Banana (من Gemini) لتوليد الصفحة كصورة طويلة. ③ ارفع الصورة هنا فتتحول إلى أقسام وعناصر نصية قابلة للتعديل. لا يلزم أي مفتاح API.</div>
  <div class="gen-steps" style="display:flex;gap:.4rem;margin:.6rem 0 1rem;flex-wrap:wrap"><button type="button" class="small gray" data-gs="1" onclick="PBGen.step(1)">① البرومبت</button><button type="button" class="small gray" data-gs="2" onclick="PBGen.step(2)">② الصورة والأقسام</button><button type="button" class="small gray" data-gs="3" onclick="PBGen.step(3)">③ التحويل</button></div>
  <div class="gen-step" data-s="1">
  <b>① البرومبت السحري المزدوج</b>
  <div class="grid2" style="margin-top:.4rem">
    <label class="hint" style="margin:0">لغة السوق (إجباري)<select id="gen-lang">${Object.keys(LANGS).map(k => `<option value="${k}">${LANGS[k].label}</option>`).join("")}</select></label>
    <label class="hint" style="margin:0">نوع العرض (إجباري)<select id="gen-offer"><option value="single">منتج واحد (Single Product)</option><option value="bundle">باك / مجموعة منتجات (Bundle)</option></select></label>
    <label class="hint" style="margin:0">اسم المنتج (اختياري)<input id="gen-name" placeholder="يقرؤه الذكاء الاصطناعي من الصورة إن تُرك فارغاً"></label>
    <label class="hint" style="margin:0">السعر (اختياري)<input id="gen-price" placeholder="مثال: 2100 دج"></label>
    <label class="hint" style="margin:0">ألوان التصميم (اختياري)<input id="gen-colors" placeholder="مثال: أزرق، برتقالي"></label>
  </div>
  <label class="hint" style="margin:.4rem 0 0">وصف أو مميزات العرض (اختياري)</label>
  <textarea id="gen-desc" rows="3" placeholder="الصق وصف منتجك ومميزاته إن أردت..."></textarea>
  <div style="display:flex;gap:.5rem;flex-wrap:wrap;margin:.5rem 0"><button class="small gold" type="button" onclick="PBGen.makePrompt()">✨ توليد البرومبت</button><button class="small gray" type="button" onclick="PBGen.copyPrompt()">📋 نسخ</button><a class="small gray" style="text-decoration:none;display:inline-block" href="https://gemini.google.com/" target="_blank" rel="noopener">فتح Gemini ↗</a><a class="small gray" style="text-decoration:none;display:inline-block" href="https://chatgpt.com/" target="_blank" rel="noopener">فتح ChatGPT ↗</a></div>
  <textarea id="gen-out" rows="8" dir="ltr" readonly placeholder="سيظهر البرومبت هنا..." style="font-size:.78rem"></textarea>
  <div style="display:flex;gap:.5rem;margin-top:.8rem;justify-content:space-between"><span></span><button class="small gold" type="button" onclick="PBGen.step(2)">التالي ←</button></div>
  </div>
  <div class="gen-step" data-s="2" style="display:none">
  <b>② ارفع الصورة الطويلة وضبط الأقسام</b>
  <div class="grid2" style="margin-top:.4rem">
    <label class="hint" style="margin:0">صورة الصفحة (من Nano Banana)<input type="file" id="gen-file" accept="image/*" onchange="PBGen.onFile(this)"></label>
    <label class="hint" style="margin:0">عدد الأقسام المتوقع<input id="gen-n" type="number" min="1" max="30" value="9" onchange="PBGen.recut()"></label>
  </div>
  <div class="grid2" style="margin-top:.4rem">
    <label class="hint" style="margin:0">محرك استخراج النصوص<select id="gen-engine" onchange="PBGen.engineUI()"><option value="tess">Tesseract — مجاني داخل المتصفح</option><option value="gemini">Gemini رؤية — أدق للعربية (بمفتاحك)</option></select></label>
    <label class="hint" style="margin:0;display:none" id="gen-gk-wrap">مفتاح Gemini API (يُحفظ في هذا المتصفح فقط)<input id="gen-gkey" dir="ltr" placeholder="AIza..." autocomplete="off" spellcheck="false" style="-webkit-text-security:disc"></label>
    <label class="hint" style="margin:0">مفتاح remove.bg (اختياري — لقص خلفية المنتج/الصور)<input id="gen-rbkey" dir="ltr" placeholder="بدونه: «قص كصورة» مستطيلة" autocomplete="off" spellcheck="false" style="-webkit-text-security:disc"></label>
  </div>
  <div style="margin:.5rem 0;display:flex;gap:.5rem;flex-wrap:wrap;align-items:center"><button class="small gold" type="button" id="gen-detect-btn" onclick="PBGen.detect()" title="يستعمل مفتاح Gemini (طبقة مجانية)">🔍 اكتشاف المنتج والصور تلقائياً</button><button class="small gray" type="button" id="gen-region-btn" onclick="PBGen.regionMode()">✂️ رسم منطقة للقص (منتج/صورة)</button><small class="hint" style="margin:0">اضغط الزر ثم اسحب مستطيلاً حول المنتج أو أي صورة في المعاينة؛ كل منطقة تصير عنصر صورة مستقلاً قابلاً للتحريك. انقر × على المنطقة لحذفها.</small></div>
  <div id="gen-prev" style="margin:.6rem 0"></div>
  <div style="display:flex;gap:.5rem;margin-top:.8rem;justify-content:space-between"><button class="small gray" type="button" onclick="PBGen.step(1)">→ السابق</button><button class="small gold" type="button" onclick="PBGen.step(3)">التالي ←</button></div>
  </div>
  <div class="gen-step" data-s="3" style="display:none">
  <b>③ التحويل إلى صفحة قابلة للتعديل</b>
  <div class="grid2" style="margin-top:.4rem">
    <label class="hint" style="margin:0">عنوان الصفحة<input id="gen-title" placeholder="مثال: عسل التركيز"></label>
    <label class="hint" style="margin:0;display:flex;gap:.4rem;align-items:center"><input type="checkbox" id="gen-ocr" checked style="width:auto"> استخراج النصوص القابلة للتعديل (OCR داخل المتصفح)</label>
    <label class="hint" style="margin:0;display:flex;gap:.4rem;align-items:center"><input type="checkbox" id="gen-erase-orig" checked style="width:auto"> امسح الأصل من الخلفية عند قص عنصر (حيث تكون الخلفية بسيطة)</label>
  </div>
  <div id="gen-sum" class="hint" style="margin:.6rem 0"></div>
  <div style="display:flex;gap:.5rem;flex-wrap:wrap;align-items:center"><button class="small" type="button" id="gen-go" onclick="PBGen.run()" disabled>🚀 تحويل إلى صفحة قابلة للتعديل</button><small id="gen-msg" style="color:var(--green);font-weight:700"></small></div>
  <div style="display:flex;gap:.5rem;margin-top:.8rem;justify-content:space-between"><button class="small gray" type="button" onclick="PBGen.step(2)">→ السابق</button><span></span></div>
  </div>
</div>`;
    try { $("gen-gkey").value = localStorage.getItem("alyssum_gp_gkey") || ""; $("gen-rbkey").value = localStorage.getItem("alyssum_removebg_key") || ""; } catch (e) { }
    step(1);
  }
  /* المعالج: 1 البرومبت ← 2 الصورة والأقسام ← 3 التحويل */
  function step(n) {
    if (n >= 2 && n === 3 && !S.canvas) { n = 2; const m = $("gen-msg"); if (m) m.textContent = "ارفع الصورة أولاً"; }
    document.querySelectorAll("#gen-card .gen-step").forEach(el => { el.style.display = Number(el.dataset.s) === n ? "" : "none"; });
    document.querySelectorAll("#gen-card [data-gs]").forEach(b => { b.className = "small " + (Number(b.dataset.gs) === n ? "gold" : "gray"); });
    S.step = n;
    if (n === 2 && S.canvas) drawPreview();
    if (n === 3) { const t = $("gen-title"); if (t && !t.value && S.file) t.value = (S.file.name || "").replace(/\.[^.]+$/, "").replace(/[-_]+/g, " ").slice(0, 60); $("gen-sum").innerHTML = S.canvas ? `سيتحول التصميم إلى <b>${S.cuts.length + 1}</b> قسماً${S.regions.length ? " مع <b>" + S.regions.length + "</b> عنصر مقصوص" : ""}. المحرك: <b>${$("gen-engine").value === "gemini" ? "Gemini رؤية" : "Tesseract"}</b>.` : "ارفع الصورة في الخطوة ②."; }
  }
  function engineUI() { $("gen-gk-wrap").style.display = $("gen-engine").value === "gemini" ? "" : "none"; }
  async function detect() {
    if (!S.canvas) return; const msg = $("gen-msg"), key = ($("gen-gkey").value || "").trim() || (function () { try { return localStorage.getItem("alyssum_gp_gkey") || ""; } catch (e) { return ""; } })();
    if (!key) { msg.textContent = "❌ أدخل مفتاح Gemini أولاً (اختر محرك Gemini ثم الصق المفتاح)"; return; }
    msg.textContent = "⏳ Gemini يبحث عن المنتج والصور…"; try { try { localStorage.setItem("alyssum_gp_gkey", key); } catch (e) { }
      const found = await (PBGen.detectFn || geminiDetect)(S.canvas, key), keep = found.filter(r => !S.regions.some(q => { const ix = Math.min(q.x1, r.x1) - Math.max(q.x0, r.x0), iy = Math.min(q.y1, r.y1) - Math.max(q.y0, r.y0); return ix > 0 && iy > 0 && ix * iy > .5 * Math.min((q.x1 - q.x0) * (q.y1 - q.y0), (r.x1 - r.x0) * (r.y1 - r.y0)); }));
      S.regions.push(...keep); drawPreview(); msg.textContent = "✅ أُضيفت " + keep.length + " منطقة — احذف (×) ما لا تريده ثم حوّل"; } catch (err) { msg.textContent = "❌ " + err.message; }
  }
  function regionMode() { S.regionMode = !S.regionMode; const b = $("gen-region-btn"); b.className = "small " + (S.regionMode ? "gold" : "gray"); b.textContent = S.regionMode ? "✂️ وضع القص مفعّل — اسحب على الصورة (انقر للإيقاف)" : "✂️ رسم منطقة للقص (منتج/صورة)"; drawPreview(); }
  function makePrompt() { $("gen-out").value = buildPrompt({ lang: $("gen-lang").value, offer: $("gen-offer").value, name: $("gen-name").value.trim(), desc: $("gen-desc").value.trim(), price: $("gen-price").value.trim(), colors: $("gen-colors").value.trim() }); }
  function copyPrompt() { if (!$("gen-out").value) makePrompt(); const t = $("gen-out").value; (navigator.clipboard ? navigator.clipboard.writeText(t) : Promise.reject()).then(() => toast("✅ نُسخ البرومبت"), () => { $("gen-out").select(); document.execCommand("copy"); toast("✅ نُسخ البرومبت"); }); }
  async function onFile(inp) {
    const f = inp.files && inp.files[0]; if (!f) return; S.file = f; S.regions = []; $("gen-msg").textContent = "⏳ جارِ قراءة الصورة…";
    try { S.canvas = await loadImage(f); } catch (e) { $("gen-msg").textContent = "❌ " + e.message; return; }
    $("gen-msg").textContent = ""; recut(); $("gen-go").disabled = false; if (!$("gen-title").value) $("gen-title").value = $("gen-name").value || f.name.replace(/\.[^.]+$/, "");
  }
  function recut() { if (!S.canvas) return; S.cuts = suggestCuts(S.canvas, Number($("gen-n").value) || 9); drawPreview(); }
  function drawPreview() {
    const C = S.canvas, host = $("gen-prev"), pw = Math.min(520, Math.max(300, (host.parentNode.clientWidth || 600) - 40)), sc = pw / C.width, ph = C.height * sc, rm = S.regionMode;
    host.innerHTML = `<div class="hint" style="margin:0 0 .3rem">${rm ? "وضع القص: اسحب مستطيلاً حول المنتج/الصورة (" + S.regions.length + " منطقة)" : "اسحب الخطوط الحمراء لضبط حدود الأقسام · انقر على الصورة لإضافة حد · انقر مرتين على خط لحذفه (" + (S.cuts.length + 1) + " أقسام)"}</div><div style="max-height:78vh;overflow:auto;border:1.5px solid var(--line);border-radius:8px;width:${pw + 18}px;max-width:100%"><div id="gen-box" style="position:relative;width:${pw}px;height:${ph}px;cursor:crosshair;background:#eee"><img src="${C.toDataURL("image/jpeg", .6)}" style="width:100%;height:100%;display:block;pointer-events:none;user-select:none">${S.cuts.map((y, k) => `<div data-cut="${k}" title="اسحب · انقر مرتين للحذف" style="position:absolute;left:0;right:0;top:${y * sc - 4}px;height:9px;cursor:ns-resize;${rm ? "pointer-events:none;opacity:.5" : ""}"><i style="display:block;height:2px;margin-top:3.5px;background:#e91e3e"></i></div>`).join("")}${S.regions.map((r, k) => `<div style="position:absolute;left:${r.x0 * sc}px;top:${r.y0 * sc}px;width:${(r.x1 - r.x0) * sc}px;height:${(r.y1 - r.y0) * sc}px;border:2px dashed #16a34a;background:rgba(22,163,74,.12)"><b data-delreg="${k}" style="position:absolute;top:-1px;right:-1px;background:#16a34a;color:#fff;padding:0 .35rem;cursor:pointer;font-size:.8rem">×</b></div>`).join("")}</div></div>`;
    const box = $("gen-box");
    box.onclick = e => { const dr = e.target.closest("[data-delreg]"); if (dr) { S.regions.splice(Number(dr.dataset.delreg), 1); drawPreview(); return; } if (rm || e.target.closest("[data-cut]")) return; const y = Math.round((e.clientY - box.getBoundingClientRect().top) / sc); S.cuts.push(y); S.cuts.sort((a, b) => a - b); drawPreview(); };
    box.ondblclick = e => { const c = e.target.closest("[data-cut]"); if (c && !rm) { S.cuts.splice(Number(c.dataset.cut), 1); drawPreview(); } };
    box.onmousedown = e => {
      const r0 = box.getBoundingClientRect();
      if (rm) { if (e.target.closest("[data-delreg]")) return; e.preventDefault(); const sx = e.clientX, sy = e.clientY, el = document.createElement("div"); el.style.cssText = "position:absolute;border:2px dashed #16a34a;background:rgba(22,163,74,.15);pointer-events:none"; box.appendChild(el);
        const mv = ev => { const x0 = Math.min(sx, ev.clientX) - r0.left, y0 = Math.min(sy, ev.clientY) - r0.top, w = Math.abs(ev.clientX - sx), h = Math.abs(ev.clientY - sy); el.style.cssText += `;left:${x0}px;top:${y0}px;width:${w}px;height:${h}px`; };
        const up = ev => { document.removeEventListener("mousemove", mv); document.removeEventListener("mouseup", up); el.remove(); const a = { x0: (Math.min(sx, ev.clientX) - r0.left) / sc, x1: (Math.max(sx, ev.clientX) - r0.left) / sc, y0: (Math.min(sy, ev.clientY) - r0.top) / sc, y1: (Math.max(sy, ev.clientY) - r0.top) / sc };
          if ((a.x1 - a.x0) * sc > 12 && (a.y1 - a.y0) * sc > 12) S.regions.push({ x0: Math.max(0, a.x0), x1: Math.min(C.width, a.x1), y0: Math.max(0, a.y0), y1: Math.min(C.height, a.y1) }); drawPreview(); };
        document.addEventListener("mousemove", mv); document.addEventListener("mouseup", up); return; }
      const c = e.target.closest("[data-cut]"); if (!c) return; e.preventDefault(); const i = Number(c.dataset.cut);
      const mv = ev => { const y = Math.max(10, Math.min(C.height - 10, Math.round((ev.clientY - r0.top) / sc))); S.cuts[i] = y; c.style.top = (y * sc - 4) + "px"; }, up = () => { document.removeEventListener("mousemove", mv); document.removeEventListener("mouseup", up); S.cuts.sort((a, b) => a - b); drawPreview(); };
      document.addEventListener("mousemove", mv); document.addEventListener("mouseup", up);
    };
  }
  async function run() {
    if (!S.canvas) return; const msg = $("gen-msg"), btn = $("gen-go"); btn.disabled = true;
    const upload = async (blob, name) => {
      try { const f = new File([blob], name + ".webp", { type: "image/webp" }); const p = await Admin.uploadImageFile(f, "assets/img/pages", "gen-", { max: 4000, q: .92, noVariants: true }); if (window.PBApp && PBApp.mediaAdd) PBApp.mediaAdd([p]); return p; }
      catch (e) { msg.textContent = "⚠️ تعذّر الرفع إلى GitHub (" + e.message + ") — حُفظت الصور مؤقتاً داخل الصفحة؛ اضبط GitHub ثم أعد التحويل للنشر."; return await new Promise(r => { const fr = new FileReader(); fr.onload = () => r(fr.result); fr.readAsDataURL(blob); }); }
    };
    try {
      const gk = $("gen-gkey").value.replace(/[\s"']/g, ""), rb = $("gen-rbkey").value.trim(), L = LANGS[$("gen-lang").value] || LANGS.ar;
      if ($("gen-engine").value === "gemini" && !gk) { msg.textContent = "أدخل مفتاح Gemini أو اختر Tesseract"; btn.disabled = false; return; }
      try { if (gk) localStorage.setItem("alyssum_gp_gkey", gk); if (rb) localStorage.setItem("alyssum_removebg_key", rb); } catch (e) { }
      const page = await convert({ canvas: S.canvas, cuts: S.cuts, regions: S.regions, rbKey: rb, eraseOrig: $("gen-erase-orig").checked, engine: $("gen-engine").value, gkey: gk, langName: L.name, ocr: $("gen-ocr").checked, tess: L.tess, title: $("gen-title").value.trim() || "صفحة هبوط", upload, onProgress: t => { msg.textContent = t; } });
      page.slug = ($("gen-title").value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")) || "lp-" + Date.now().toString(36).slice(-4);
      msg.textContent = "✅ تم — جارِ فتح المحرر"; PBApp.open(page, "", true);
    } catch (e) { console.error(e); msg.textContent = "❌ " + e.message; }
    btn.disabled = false;
  }
  return { LANGS, buildPrompt, loadImage, suggestCuts, groupLines, analyze, erase, refineBox, geminiOcr, geminiDetect, detect, detectFn: null, removeBgCall, cropBlob, convert, mount, makePrompt, copyPrompt, onFile, recut, run, engineUI, regionMode, step, ocr: null, removeBg: null };
})();
